ash-project/ash_hq

assets/css/app.css
lib/ash_hq_web/pages/docs.ex

* Adjusted spacing between the sidebars and main docs to maintain consistent width regardless of the content
* Added a custom scrollbar

Docs sizing and custom scrollbar

---

mix.exs

While setting up a local dev instance of ash_hq, I ran into errors due to the UAInspector DB not being downloaded automatically.
This PR adds a command to the setup task alias to download the required files (per instructions at https://github.com/elixir-inspector/ua_inspector#database-download).
Not sure if it is better as part of the `setup` task or just a documented step in the README.md ?

fix: download user agent db in setup task

---

.tool-versions

This PR adds nodejs to the ASDF `.tool-versions` file to fix an error at startup if there isn't a global nodejs installed:
```
iex -S mix phx.server
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
[notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
[info] Running AshHqWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access AshHqWeb.Endpoint at http://localhost:4000
Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> No version is set for command npx
Consider adding one of the following versions in your config file at /Users/michaelbuhot/src/ash-project/ash_hq/.tool-versions
nodejs 14.17.0
nodejs 16.17.0
nodejs lts
nodejs 16.18.0
nodejs 18.12.0
[watch] build finished, …
```

chore: Add nodejs 18 (LTS) to .tool-versions

---

lib/ash_hq_web/pages/docs.ex

fixes #38 
Having a unique ID on the div surrounding the docs forces morphdom to treat it as a distinct node.
Morphdom will now append the new content and delete the old content, rather than merging the content node-by-node.

fix: Workaround morphdom incorrectly merging docs headings 

---

.gitignore
assets/css/app.css
config/config.exs
config/dev.exs
lib/ash_hq_web/components/doc_sidebar.ex
lib/ash_hq_web/components/doc_sidebar_dsl_items.ex
lib/ash_hq_web/components/tree_view.ex
mix.exs

Fixes #33 
This PR makes some changes to the sidebar tree view, giving more consistency to the selection and collapsing experience.
---
By default the reference section is collapsed, with the guides section expanded:
The extensions now include the chevron icon to indicate they can be expanded:
Selection works uniformly throughout, so the previous behaviour of bolding all nodes on the path to the currently selected DSL is lost. (It can be added this back in if desired):

Improvements to docs sidebar

---

.github/ISSUE_TEMPLATE/bug.md

When previewing the generated text, it rendered as `** Brief Description **`, etc.
Also tidied up filename and updated the description for the steps (was leftover from copying from a previous issue template)

chore: Update bug issue template to use valid Markdown

---

assets/css/app.css
lib/ash_hq_web/components/app_view/top_bar.ex
lib/ash_hq_web/pages/docs.ex

This PR fixes the border colours around the top bars, left sidebar and the scrollbar styling when in dark mode.

fix: Dark mode borders and scrollbars

---

lib/ash_hq/application.ex
mix.exs

By default Mix will start the applications in all dependencies, which in this case will raise an error if there isn't a valid Discord bot token set.

fix: Only start Nostrum when the Discord bot is enabled

---

.formatter.exs
assets/tailwind.config.js
lib/ash_hq/docs/extensions/render_markdown/changes/render_markdown.ex
lib/ash_hq/docs/extensions/render_markdown/post_processor.ex
lib/ash_hq/docs/extensions/render_markdown/post_processors/heading_autolinker.ex
lib/ash_hq/docs/extensions/render_markdown/post_processors/highlighter.ex
lib/ash_hq/docs/extensions/render_markdown/post_processors/table_of_contents_generator.ex
lib/ash_hq/docs/extensions/render_markdown/render_markdown.ex
lib/ash_hq/docs/resources/guide/guide.ex

* Refactors how the `RenderMarkdown` extension generates its HTML, to allow for multiple post-processors to be piped together. Each post-processor takes a Floki AST, can do whatever it wants, and returns a new Floki AST. At the end, the AST is converted to HTML.
* Adds a new post-processor for generating tables of contents for rendered documents
* This post-processor will take any second and third level headings from documents (first-level is the page heading) and build links to each section of the document.
* This functionality can be turned on/off per resource via a new `table_of_contents?` option, and currently is enabled for Guides only.
The table of contents looks like this:
It isn't fixed, it floats to the right, so it will scroll with the screen content. Any design advice welcome! …

improvement: Table of Contents for guides

---

assets/js/app.js
lib/ash_hq/docs/extensions/render_markdown/post_processors/table_of_contents_generator.ex

Uses a tiny JS hook on generated tables of contents to show overflowing text in `title` attributes.
(screenshot didn't capture my mouse but I'm hovering the link)
(To get this for current versions of docs, a rebuild will be required)
We don't seem to have anything within the project for JS formatting, so my editor changed things quite a bit - I didn't include (most of) what it changed but there might be some churn.

improvement: Show overflowing text as a `title` tooltip in table of contents

---

lib/ash_hq/docs/extensions/render_markdown/changes/render_markdown.ex

As discussed on Slack - turns out to be a really simple fix (but this doesn't solve the potential underlying architectural issue).
Something unexpected was happening when setting the `library_version_id` of imported guides, which meant that the `current_library` was nil. If the `current_library` was nil, the Highlighter post-processor was ignoring links instead of rewriting them to be AshHQ links.
Before (the security guide link):
After: link is correctly rewritten to http://(domain)/docs/guides/ash/latest/security .
Have tested by running a full import locally and all of the other broken links I noticed have also been fixed.

fix: Links to guides are now correctly converted to AshHQ links on import

---

assets/tailwind.config.js
lib/ash_hq/docs/extensions/render_markdown/post_processors/heading_autolinker.ex
lib/ash_hq/docs/extensions/render_markdown/post_processors/table_of_contents_generator.ex
lib/ash_hq_web/components/tag.ex

Wrapping the headings with margins in parent divs (to allow for autolinking) was preventing margins from collapsing, making spacing between elements way too big
| Before | After |
|--------|-------|
| <img width="549" alt="Screenshot 2023-01-25 at 3 08 27 pm" src="https://user-images.githubusercontent.com/543859/214501570-8ec1d358-b6f5-4588-9c2a-2f7fd5eff9e6.png"> | <img width="562" alt="Screenshot 2023-01-25 at 3 08 35 pm" src="https://user-images.githubusercontent.com/543859/214501580-de5c4d71-d00b-4874-8d0c-2a6c3f594b08.png"> |
ps. I snuck another tiny style fix in there for "required" pills:
| Before | After |
|--------|-------|
| <img width="163" alt="Screenshot 2023-01-25 at 3 17 11 pm" src="https://user-images.githubusercontent.com/543859/214502829-0405a6e8-b3df-4b63-a720-1337825306 …

improvement: Allow heading margins to collapse in guide content

---

lib/ash_hq_web/components/search.ex

I noticed yesterday that the Search box doesn't actually close when you click on a result - the page URL changes, the new content is shown, but an empty search box is also shown. Now it closes so you can see what you selected!

fix: Close the Search box when a search result is selected

---

assets/js/app.js
lib/ash_hq_web/plugs/session_plug.ex
lib/ash_hq_web/templates/layout/root.html.eex
lib/ash_hq_web/views/app_view_live.ex

Fixes bug where selected libraries are not being remembered across sessions. The cookie banner was accidentally removed, and without consent being given, we don't set any cookies.
(Also a cleanup because we *were* actually setting a theme cookie in duplicated code, and a bit of refactoring during debugging).

fix: Remember selected library versions

---

lib/ash_hq_web/components/search.ex

* Fixes a bug where on small screens, the library picker at the bottom of the search modal would overflow the modal
* Tweaks the layout of the modal content, lining things up and removing the big heavy backgrounds
Before:
After:
(I'm not sure why the build is failing, but it's also failing in main for the same reason)

improvement: Search modal UI

---

lib/ash_hq_web/pages/home.ex

So I noticed a weird rendering bug on the homepage in Firefox - looks like this
I'm not sure exactly what causes it, but this tweak (moving from `space-y-8` to `mt-8` top on the elements) seems to fix it?

fix: Tweak how testimonials are laid out to fix a rendering issue in Firefox

---

assets/js/app.js
lib/ash_hq_web/components/catalogue.ex
lib/ash_hq_web/components/catalogue_modal.ex
lib/ash_hq_web/components/search.ex
lib/ash_hq_web/pages/docs.ex
lib/ash_hq_web/plugs/session_plug.ex
lib/ash_hq_web/views/app_view_live.ex

Two goodies today, both related to the catalogue of libraries that can be enabled/disabled - 
* Redesigns the catalogue to be an aligned grid of libraries
* Shows enabled libraries in the primary colour, and condenses the "latest"/latest numbered version options in the dropdown
Originally I thought of hiding the dropdowns, and showing a toggle to enable/disable the library (which would then show the dropdown and have the latest version selected) but I think this is okay.
* As discussed on Discord the other day, adds a reeeally big call to action to point users to the catalogue, to see what libraries are available. (Blue because its the opposite colour of orange and I wanted this baby to stand out.) Clicking it opens the catalogue, with a tip of how to get back here (once they dismiss the …

improvement: Catalogue UI

---

assets/js/app.js
assets/package-lock.json
assets/package.json
lib/ash_hq_web/pages/docs.ex
lib/ash_hq_web/templates/layout/root.html.eex

As discussed. It is *super big* and we're not using it anywhere anyway?
In testing in dev (uncompressed/unminified/etc.)
* app.js with mermaid included: 7.58MB
* app.js without mermaid included: 700kB
Testing building for prod:
* currently in prod: 504kB
* testing esbuild without mermaid: 103kB

chore: remove mermaid.js

---

lib/ash_hq_web/pages/home.ex

A lot of the classes were subtly different - now the only thing that needs to change is the margin that creates the overlapping effect
---
The bug this was originally fixing was the testimonials overlapping the following contributors div. 
It was overlapping on my screen too, but not as much. The testimonials div had a fixed height, but variable contents - and some weird margins, paddings, etc. I tried to simplify the HTML a lot and fix some CSS issues.
(There was also a really weird glitch with `drop-shadow` in Firefox - I initially tried to fix it in #85 but tweaking things here made it come back.... switching to `shadow` instead appears to have fixed it for good. Fingers crossed. I tested it in FF on two different macOS laptops and one Windows laptop, and no issues.)

chore: Extract testimonials to shared function component

---

lib/ash_hq_web/helpers.ex
lib/ash_hq_web/pages/docs.ex

Closes #37
It looks like this: 
And works okay when the text wraps:
The problem with doing this, though, is that because we're linking to released versions of a guide at a given tag, an end user can't simply fork-and-edit to fix any typos/other content.
Should we actually link to main instead of the tag, to be forkable/editable, but then what they see on GitHub isn't necessarily what they were just reading on AshHQ?

feature: Add link to the source for the currently-viewed guide on GitHub

---

lib/ash_hq_web/doc_routes.ex

Closes #101
Now searching for options with names with special characters (such as `sensitive?` or `generated?`) returns links with correctly sanitized URLs, such as `http://localhost:4000/docs/dsl/ash/latest/resource/attributes/uuid_primary_key#generated-`

fix: Sanitize option names in search result links

---

lib/ash_hq_web/components/version_pills.ex

Trying to get back into contributing so bear with me 😅
Small accessibility tweak as per https://github.com/ash-project/ash_hq/issues/34
Increases the clickable area of the button to remove an included library in the sidebar. As was mentioned in the issue we don't have the space for a full 44 x 44 px button but hopefully this makes things a little easier to use.

fix: Increase clickable area of button to remove a library in sidebar

---

lib/ash_hq_web/pages/home.ex

APS is a better landing page for talking to an expert

Point to APS

---

assets/js/app.js

This is a dead link: https://hexdocs.pm/live_debugger/readme.html - it now goes to https://hexdocs.pm/live_debugger/welcome.html
However, to prevent it from ever being a problem again, I've removed the html reference to allow hexdocs to redirect you to the right place.
Resolves https://github.com/ash-project/ash_hq/issues/303

fix(app.js): replace dead live_debugger doc link
